recipe: default.v1
language: en

pipeline:
- name: CompactLLMCommandGenerator
  llm:
    provider: mistral
    model: mistral/codestral-2405
  flow_retrieval:
    active: false

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
  vector_store:
    type: "faiss"
    source: "./docs"
  llm:
    provider: mistral 
    model: mistral/codestral-2405
  embeddings:
    provider: mistral
    model: mistral/mistral-embed

assistant_id: 20250322-083039-ash-paddle
